name: Release Resume
on: 
  push:
    branches:
      main
jobs:
  Compile-Resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: weedon_resume.tex
          latexmk_use_lualatex: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: Resume
          path: weedon_resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: my_resume
          files: weedon_resume.pdf
