name: Compile Resume
on: [push]
jobs:
  Compile-Resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: weedon_resume.tex
          latexmk_use_lualatex: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: Resume
          path: weedon_resume.pdf
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}
          files: weedon_resume.pdf
